[package]
name = "ray_tracing_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.7"
indicatif = "0.16.2"
rand = "0.8.5"
nalgebra = "0.31.0"